/*!
 * Cafe Phố Xưa V8.7 - Production UI Controller
 * Cart / remembered customer / order image + text sharing for Zalo
 */
(function (window, document) {
'use strict';
const Core = window.CafePhoXua;
if (!Core || !Core.Cart) { console.error('[CafePhoXua.UI] Core/Cart chưa sẵn sàng.'); return; }
const Cart = Core.Cart;
const CART_KEY='cart.v8', CUSTOMER_KEY='customer.v1', LAST_ORDER_KEY='lastOrder.v1';
const ZALO_PHONE='0868708799';
const $=id=>document.getElementById(id);
const money=v=>Number(v||0).toLocaleString('vi-VN')+'đ';
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
function saveCart(){try{Core.storage.set(CART_KEY,Cart.getItems());localStorage.removeItem('cafePhoXuaCart');}catch(e){console.warn(e);}}
function restoreCart(){let items=Core.storage.get(CART_KEY,null);if(!Array.isArray(items)){try{items=JSON.parse(localStorage.getItem('cafePhoXuaCart')||'[]');}catch(_){items=[];}}if(!Array.isArray(items)||!items.length||Cart.hasItems())return;items.forEach(i=>{if(!i||!(i.name||i.product))return;Cart.addItem({name:i.name||i.product,price:Number(i.price)||0,quantity:Math.max(1,Number(i.quantity)||1),note:i.note||'',sugar:i.sugar??100,ice:i.ice??100,toppings:Array.isArray(i.toppings)?i.toppings:[]});});saveCart();}
function getCustomerProfile(){const p=Core.storage.get(CUSTOMER_KEY,null);return p&&typeof p==='object'?p:null;}
function restoreCustomerProfile(){const p=getCustomerProfile();if(!p)return;if($('customerName')&&!$('customerName').value)$('customerName').value=p.name||'';if($('customerPhone')&&!$('customerPhone').value)$('customerPhone').value=p.phone||'';if($('customerAddress')&&!$('customerAddress').value)$('customerAddress').value=p.address||'';}
function saveCustomerProfile(order){try{Core.storage.set(CUSTOMER_KEY,{name:order.customer.name.trim(),phone:order.customer.phone.trim(),address:order.customer.address.trim(),savedAt:Date.now()});}catch(e){console.warn(e);}}
function saveLastOrder(order,message){try{Core.storage.set(LAST_ORDER_KEY,{order,message,savedAt:Date.now()});}catch(e){console.warn(e);}}
function ensureFloatingCart(){let b=$('floatingCartSummary');if(b)return b;const s=document.createElement('style');s.id='cpx-floating-cart-style';s.textContent='#floatingCartSummary{display:none;position:fixed;left:50%;bottom:18px;transform:translateX(-50%);z-index:9999;border:0;border-radius:999px;padding:13px 20px;background:#6f451f;color:#fff;font-weight:800;box-shadow:0 10px 30px rgba(0,0,0,.25);cursor:pointer;white-space:nowrap}@media(min-width:769px){#floatingCartSummary{display:none!important}}';document.head.appendChild(s);b=document.createElement('button');b.id='floatingCartSummary';b.type='button';b.setAttribute('aria-label','Mở giỏ hàng');b.addEventListener('click',openCart);document.body.appendChild(b);return b;}
function renderCart(){const list=$('cart-items'),count=$('cart-count'),totalEl=$('cart-total');if(!list||!count||!totalEl)return;const items=Cart.getItems(),summary=Cart.getSummary();count.textContent=String(summary.itemCount||0);totalEl.textContent='Tổng tiền: '+money(summary.total);const f=ensureFloatingCart();f.textContent=`🛒 ${summary.itemCount||0} món • ${money(summary.total)}`;f.style.display=summary.itemCount>0?'block':'none';if(!items.length){list.innerHTML='<p class="cart-empty" style="text-align:center;padding:20px;">Chưa có sản phẩm.</p>';return;}list.innerHTML=items.map(item=>`<div class="cart-item" data-cart-id="${esc(item.id)}"><div class="cart-item-info"><strong>${esc(item.name)}</strong><div>${money(item.price)} × ${item.quantity}</div></div><div class="cart-qty"><button type="button" data-cart-action="minus" data-cart-id="${esc(item.id)}">−</button><span>${item.quantity}</span><button type="button" data-cart-action="plus" data-cart-id="${esc(item.id)}">+</button></div><div><strong>${money(Number(item.price)*Number(item.quantity))}</strong></div></div><hr>`).join('');}
function renderPaymentSummary(){const list=$('paymentOrderList'),totalEl=$('paymentTotalPrice');if(!list||!totalEl)return;const items=Cart.getItems(),summary=Cart.getSummary();list.innerHTML=items.length?items.map(i=>`<div class="payment-item"><div><strong>${esc(i.name)}</strong></div><div>SL: ${i.quantity}</div><div>${money(Number(i.price)*Number(i.quantity))}</div><hr></div>`).join(''):'<p>Chưa có sản phẩm.</p>';totalEl.textContent=money(summary.total);}
function addToCart(name,price){name=String(name||'').trim();price=Number(price)||0;if(!name)return false;const ex=Cart.findFirst(i=>i.name===name&&Number(i.price)===price);if(ex)Cart.increaseQuantity(ex.id,1);else Cart.addItem({name,price,quantity:1});return true;}window.addToCart=addToCart;
function openCart(){renderCart();const p=$('cart-popup');if(p)p.style.display='flex';}
function closeCart(){const p=$('cart-popup');if(p)p.style.display='none';}
function openPayment(){if(Cart.isEmpty()){alert('Giỏ hàng đang trống. Vui lòng chọn ít nhất một món.');return;}restoreCustomerProfile();renderPaymentSummary();closeCart();const o=$('paymentOverlay');if(o)o.style.display='flex';}
function closePayment(){const o=$('paymentOverlay');if(o)o.style.display='none';}
function validateCustomer(){const fields=[[ $('customerName'),'Vui lòng nhập họ và tên.' ],[ $('customerPhone'),'Vui lòng nhập số điện thoại.' ],[ $('customerAddress'),'Vui lòng nhập địa chỉ giao hàng.' ]];for(const [input,msg] of fields){if(!input)continue;input.style.borderColor='';if(!input.value.trim()){alert(msg);input.style.borderColor='red';input.focus();return false;}}const p=$('customerPhone');if(p){const n=p.value.replace(/[\s.()-]/g,'');if(!/^(?:\+84|0)\d{9}$/.test(n)){alert('Số điện thoại chưa đúng định dạng Việt Nam.');p.style.borderColor='red';p.focus();return false;}}return true;}
function buildOrder(){return{customer:{name:$('customerName')?.value.trim()||'',phone:$('customerPhone')?.value.trim()||'',address:$('customerAddress')?.value.trim()||'',note:$('customerNote')?.value.trim()||''},items:Cart.getItems(),total:Cart.getSummary().total};}
function fallbackOrderMessage(order){const a=['☕ CAFE PHỐ XƯA','','🛒 ĐƠN ĐẶT ĐỒ UỐNG','',`👤 Khách hàng: ${order.customer.name}`,`📞 Điện thoại: ${order.customer.phone}`,`📍 Địa chỉ: ${order.customer.address}`,`📝 Ghi chú: ${order.customer.note||'Không có'}`,'','📋 DANH SÁCH MÓN'];order.items.forEach((i,k)=>{a.push(`${k+1}. ${i.name}`);a.push(`   SL: ${i.quantity} × ${money(i.price)}`);a.push(`   Thành tiền: ${money(Number(i.price)*Number(i.quantity))}`);});a.push('',`💰 TỔNG THANH TOÁN: ${money(order.total)}`,'','❤️ Cảm ơn Quý khách!');return a.join('\n');}
function buildOrderMessage(order){try{if(window.CafePhoXuaOrderBuilder?.buildOrderMessage)return window.CafePhoXuaOrderBuilder.buildOrderMessage(order);}catch(e){console.warn(e);}return fallbackOrderMessage(order);}
async function copyOrderMessage(message){try{if(navigator.clipboard?.writeText){await navigator.clipboard.writeText(message);return true;}}catch(_){}try{const t=document.createElement('textarea');t.value=message;t.setAttribute('readonly','');t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();const ok=document.execCommand('copy');t.remove();return ok;}catch(_){return false;}}
function wrapText(ctx,text,maxWidth){const words=String(text||'').split(/\s+/);const lines=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word;}else line=test;}if(line)lines.push(line);return lines;}
function canvasToBlob(canvas){return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Không tạo được ảnh đơn hàng.')),'image/png',0.95));}
async function makeOrderImageFile(order){const width=1080,pad=70;const c=document.createElement('canvas');const ctx=c.getContext('2d');ctx.font='34px Arial';const detail=[];detail.push(['Khách hàng',order.customer.name]);detail.push(['Điện thoại',order.customer.phone]);detail.push(['Địa chỉ',order.customer.address]);detail.push(['Ghi chú',order.customer.note||'Không có']);order.items.forEach((i,k)=>detail.push([`${k+1}. ${i.name}`,`SL ${i.quantity} × ${money(i.price)} = ${money(Number(i.price)*Number(i.quantity))}`]));let height=360;for(const [l,r] of detail){height+=54+wrapText(ctx,r,width-pad*2).length*44;}height+=170;c.width=width;c.height=Math.max(height,900);ctx.fillStyle='#fffaf5';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#562b13';ctx.font='bold 58px Georgia, serif';ctx.fillText('CAFE PHỐ XƯA',pad,100);ctx.font='bold 38px Arial';ctx.fillStyle='#7d3e17';ctx.fillText('ĐƠN ĐẶT ĐỒ UỐNG',pad,160);ctx.strokeStyle='#d8c4b4';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(pad,195);ctx.lineTo(width-pad,195);ctx.stroke();let y=255;for(const [label,value] of detail){ctx.fillStyle='#3d2415';ctx.font='bold 31px Arial';ctx.fillText(label,pad,y);y+=42;ctx.font='30px Arial';ctx.fillStyle='#4d4038';for(const line of wrapText(ctx,value,width-pad*2)){ctx.fillText(line,pad,y);y+=42;}y+=22;}ctx.strokeStyle='#d8c4b4';ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(width-pad,y);ctx.stroke();y+=65;ctx.fillStyle='#b53825';ctx.font='bold 42px Arial';ctx.fillText('TỔNG THANH TOÁN: '+money(order.total),pad,y);y+=75;ctx.fillStyle='#6b5c50';ctx.font='27px Arial';ctx.fillText('Zalo/Điện thoại quán: '+ZALO_PHONE,pad,y);const blob=await canvasToBlob(c);return new File([blob],`don-hang-cafe-pho-xua-${Date.now()}.png`,{type:'image/png'});}
async function shareOrderToZalo(order,message){await copyOrderMessage(message);let file=null;try{file=await makeOrderImageFile(order);}catch(e){console.warn('[CafePhoXua.UI] Không tạo được ảnh đơn.',e);}if(navigator.share){try{const payload={title:'Đơn hàng Cafe Phố Xưa',text:message};if(file&&navigator.canShare?.({files:[file]}))payload.files=[file];await navigator.share(payload);return{ok:true,mode:file?'share-image':'share-text'};}catch(e){if(e?.name==='AbortError')return{ok:false,cancelled:true};console.warn('[CafePhoXua.UI] Share thất bại.',e);}}alert('Đơn hàng đã được sao chép. Zalo sẽ mở ngay. Hãy Dán nội dung vào khung chat và bấm Gửi.');window.location.href=`https://zalo.me/${ZALO_PHONE}`;return{ok:true,mode:'copy'};}
async function sendOrder(){if(Cart.isEmpty()){alert('Giỏ hàng đang trống.');return false;}if(!validateCustomer())return false;const order=buildOrder();const message=buildOrderMessage(order);saveCustomerProfile(order);saveCart();saveLastOrder(order,message);const result=await shareOrderToZalo(order,message);if(!result.ok&&result.cancelled)return false;closePayment();const success=$('successOverlay');if(success)success.style.display='flex';return true;}
function finishOrder(){const s=$('successOverlay');if(s)s.style.display='none';Cart.clearCart();Core.storage.remove(CART_KEY);localStorage.removeItem('cafePhoXuaCart');if($('customerNote'))$('customerNote').value='';renderCart();}
function bindUI(){$('cart-icon')?.addEventListener('click',openCart);$('close-cart')?.addEventListener('click',closeCart);$('btnOpenPaymentPopup')?.addEventListener('click',openPayment);$('closePaymentPopup')?.addEventListener('click',closePayment);$('btnContinueShopping')?.addEventListener('click',()=>{closePayment();$('menu')?.scrollIntoView({behavior:'smooth',block:'start'});});$('btnSendZaloOrder')?.addEventListener('click',async e=>{e.preventDefault();const b=e.currentTarget,old=b.textContent;b.disabled=true;b.textContent='Đang tạo đơn...';try{await sendOrder();}finally{b.disabled=false;b.textContent=old;}});$('btnSuccessDone')?.addEventListener('click',finishOrder);$('cart-popup')?.addEventListener('click',e=>{if(e.target===$('cart-popup'))closeCart();});$('paymentOverlay')?.addEventListener('click',e=>{if(e.target===$('paymentOverlay'))closePayment();});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeCart();closePayment();}});$('cart-items')?.addEventListener('click',e=>{const b=e.target.closest('[data-cart-action]');if(!b)return;const id=b.dataset.cartId,i=Cart.getItem(id);if(!i)return;if(b.dataset.cartAction==='plus')Cart.increaseQuantity(id,1);if(b.dataset.cartAction==='minus')i.quantity<=1?Cart.removeItem(id):Cart.decreaseQuantity(id,1);});}
function loadBranding(){if(document.querySelector('script[data-cpx-branding]'))return;const s=document.createElement('script');s.src='CafePhoXua.Branding.js?v=8.7.0-20260913';s.dataset.cpxBranding='true';document.head.appendChild(s);}
function loadLocalSeo(){if(document.querySelector('script[data-cpx-local-seo]'))return;const s=document.createElement('script');s.src='CafePhoXua.LocalSEO.js?v=1.0.0-20260913';s.dataset.cpxLocalSeo='true';document.head.appendChild(s);}
function init(){restoreCart();restoreCustomerProfile();bindUI();Cart.on('cart:change',()=>{saveCart();renderCart();if($('paymentOverlay')?.style.display==='flex')renderPaymentSummary();});renderCart();loadBranding();loadLocalSeo();console.log('☕ Cafe Phố Xưa V8.7 UI READY');}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})(window,document);